### ISSUE TITLE
Omon table variable dbze dimension 01.00.08

### ISSUE THREAD

**Issue by dnadeau4** [cmip6dr/dreqPy#10]
Omon variables
============
I found a lot variables in Omon that had `dbze` has a new dimension.  
`dbze` is used for radar reflectivity....

Can you check all Omon variables with dbze dimensions in your database?
Example:
 * [hfbasin](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Omon.json#L1751)

CMOR failed and I fixed the test before releasing the latest `01.00.08` tables, but later realized that this did not seem to be right.

CMOR test failed
=============
!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: You are defining variable 'htovgyre' (table Omon)  with 3 dimensions, when it should have 4
!
!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by martinjuckes** [comment]
Fixed
