### ISSUE TITLE
DCPP dynvar data

### ISSUE THREAD

**Issue by DougSmithMO** [cmip6dr/dreqPy#14]
In our GMD paper we also encourage participants to retain some variables to support DynVarMIP and diagnose solar effects. However, these are not currently included in our data request and may not be picked up. Would it be possible to add these as priority 3 to the DCPP data request please, just to make sure that groups pick them up? The variables are:

Amon:
* air temperature (ta), plev39 (longitude latitude plev39 time)
* eastward wind (ua), plev39 (longitude latitude plev39 time)
Note: these are already requested on plev19, but additional levels are requested

EmonZ:
* Upward Component of the Eliassen-Palm Flux (epfz) (longitude: mean) (latitude plev39 time)
* Northward Component of the Eliassen-Palm Flux (epfy) (longitude: mean) (latitude plev39 time)
* Transformed Eulerian mean northward wind (vtem) (longitude: mean) (latitude plev39 time)
* Transformed Eulerian mean upward wind (wtem) (longitude: mean) (latitude plev39 time)
* Tendency of eastward wind due to Eliassen-Palm Flux divergence (utendepfd) (longitude: mean) (latitude plev39 time)
* Eastward wind (ua) (longitude: mean) (latitude plev39 time)

**Comment by martinjuckes** [comment]
@DougSmithMO : the plev39 ta, ua variables requested by DynVar are zonal means in table AERmonZ: are these the ones you mean? We don't currently have any data with dimensions (longitude latitude plev39 time). It could be added, but DynVar do not need it.

**Comment by martinjuckes** [comment]
resolved.
