### ISSUE TITLE
Question about Data Request 

### ISSUE THREAD

**Issue by aearamos** [cmip6dr/dreqPy#19]
Hi, @martinjuckes 

I've been using the drq command here at BSC to implement a DCPP Input/Output
option for Ec-earth. As I was playing with different Tiers and
Priorities in drq, I came across a few questions and I was hoping you
could help me.

First, when I was comparing the variables from cmvmm_DCPP_CMIP_1_1.xlsx
and cmvmm_DCPP_CMIP_3_3.xlsx, I noticed that the data request for Tier 3
and Priority 3 (cmvmm_DCPP_CMIP_3_3.xlsx) would give me some variables
that are Priority 1, but that don't appear when I ask for Tier 1,
Priority 1 (cmvmm_DCPP_CMIP_1_1.xlsx). Some of these variables are Sea
Water Velocity (X and Y), Sea Surface Salinity and Sea Water Salinity,
among others.

I understand each MIP have its own properties and minimum set of
variables, but shouldn't all the Priority 1 variables that appear in
Tier 3, Priority 3 also appear in drq Tier 1, Priority 1?

This is for dreqPy version 01.00.21 [Version 01.00.21].

Thanks.

**Comment by martinjuckes** [comment]
Hello,  MIPs can specify different priorities when they request a variable. The way that this is presented in the summary sheets is a bit confusing .. sorry about that. If a CMOR variable has default priority 1 but is requested by DCPP at priority 3, it will not appear in the cmvmm_DCPP_CMIP_1_1.xlsx file.

The confusing part is that cmvmm_DCPP_CMIP_3_3.xlsx lists the default priority, not the actual requested priority. These sheets were developed to provide an overview of the request, they don't provide all the information. 

regards,
Martin

**Comment by aearamos** [comment]
Hi, @martinjuckes. Yes, I figured that out later. One variable can have a default priority of 2, but that priority may vary depending on the MIP. I had to dig a little deeper in the summary_sheets, but it's all clear to me now. 

Thanks!
