### ISSUE TITLE
Default priorities in the sheets generated by command line

### ISSUE THREAD

**Issue by martinjuckes** [cmip6dr/dreqPy#2]
The priorities specified by a MIP may differ from priorities appearing in a sheet produced by the command line because the priorities in the sheet represent the default priority of a variable which may be requested by several MIPs at different priorities .. the presentation is not ideal.

**Comment by jaanstey** [comment]
Thanks Martin. For the DCPP request, I see that out of 115 variable that agree between the spreadsheet (cmvmm_DCPP_TOTAL_3_3.xlsx) and the original DCPP request, the priority in the spreadsheet less than or equal to the priority given in the original request (where "less than" of course indicates higher priority). There are only two exceptions, which are the vsf and zossq variables from Omon.  

Are the priorities given in this spreadsheet:
  http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/CMIP6_MIP_tables.xlsx
set in the same way? That is, the priority given for a variable in this spreadsheet is the minimum value over all MIPs that have requested the variable - is that correct?

Thanks,
James

**Comment by martinjuckes** [comment]
Hello James,  
Yes, the variable priorties should now show the minimum requested.
