### ISSUE TITLE
spread sheet view improvement

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/dreqPy#4]
Hi Martin,

The spreadsheets produced by drq would be much easier to work with if you increase the width of a few of the columns (notably U, V, AA, AB, and AE). That way the user could view many more variables at once.  (Alternatively, you could make it so that in those columns the text doesn't wrap.)

thanks,
Karl

**Comment by martinjuckes** [comment]
Changes made for inclusion in 01.00.02
