### ISSUE TITLE
Inconsistent dreq versioning numbers

### ISSUE THREAD

**Issue by matthew-mizielinski** [cmip6dr/dreqPy#6]
The following code demonstrates a conflict in the version numbers within the data request;

```
>>> from dreqPy import dreq
>>> dq = dreq.loadDreq()
>>> print dq.version
01.00.00
>>> print dq.softwareVersion
01.00.01
>>> print dq.c.version
01.00.00
```
I'm fairly confident that dreqPy is reading the correct xml file (I've hidden the one I have in the true version 1.00.00 installation).

This error affects the audit trails within our systems.

**Comment by martinjuckes** [comment]
Fixed
