### ISSUE TITLE
Possible error in MIP link label/tab generation (PMIP case) ?

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/dreqPy#9]
The following uses version 1.00.06

@martinjuckes when I use the **label** of a table link, when trying to use dreqPy to look at the PMIP part of the DR, there are labels with **PMIP-table** (eg _PMIP-Amon_) and others with **PMIP-PMIP-table** (eg _PMIP-PMIP-Omon_). I have not found the logic of this. And using **tab** instead of _label_ is also confusing. Could there be a bug? I'm not very comfortable with the dreqPy API, so I may have done something wrong!

I have used the following script:
```
#!/usr/bin/env

from dreqPy import dreq, scope

select_mip = 'PMIP'

# Get the tables associated with the project
sc = scope.dreqQuery()
mip_links = sc.getRequestLinkByMip(select_mip)

mip_links_dic = {}
for ml in mip_links:
    mip_links_dic[ml.label] = ml
    #mip_links_dic[ml.tab] = ml

mip_links_skeys = sorted(mip_links_dic.keys())
for mip_table in mip_links_skeys:
    print mip_table
```
And I get this if I use **label** (everything has a **PMIP-** prefix, except **fx**):
```
PMIP-6hrLev
PMIP-Amon
PMIP-Amon-02
PMIP-CFday
PMIP-CFmon
PMIP-LImon
PMIP-Lmon
PMIP-Lmon-02
PMIP-Omon-02
PMIP-Oyr
PMIP-PMIP-6hr
PMIP-PMIP-Aclim
PMIP-PMIP-LIclim
PMIP-PMIP-Lclim
PMIP-PMIP-OIclim
PMIP-PMIP-Oclim
PMIP-PMIP-Omon
PMIP-PMIP-aeroclim
PMIP-SImon
PMIP-aero
PMIP-aero-02
PMIP-day
PMIP-day-02
fx
```
and this if I use **tab** (things start with either **PMIP-** or **PMIP.**, except **fx**):
```
PMIP-Amon-02
PMIP-Lmon-02
PMIP-Omon-02
PMIP-SImon
PMIP-aero-02
PMIP-day-02
PMIP.6hrLev
PMIP.Amon
PMIP.CFday
PMIP.CFmon
PMIP.LImon
PMIP.Lmon
PMIP.Oyr
PMIP.PMIP-6hr
PMIP.PMIP-Aclim
PMIP.PMIP-LIclim
PMIP.PMIP-Lclim
PMIP.PMIP-OIclim
PMIP.PMIP-Oclim
PMIP.PMIP-Omon
PMIP.PMIP-aeroclim
PMIP.aero
PMIP.day
fx

```

**Comment by martinjuckes** [comment]
These are groups, rather than tables ... I'm sorry the naming is confusing. This arose because of the multiple input routes which needed to be maintained. I've now reorganised this, so it should be easier for me to review these names ... though it is still not a priority.
